from django.urls import path
from .views import (
    CarrouselList, CarrouselCreate, CarrouselUpdate, CarrouselDelete,
    MorceauList, MorceauCreate, MorceauUpdate, MorceauDelete,
    EvenementList, EvenementCreate, EvenementUpdate, EvenementDelete,
    AudioList, AudioCreate, AudioUpdate, AudioDelete,
    AlbumList, AlbumCreate, AlbumUpdate, AlbumDelete,
    DiscographieList, DiscographieCreate, DiscographieUpdate, DiscographieDelete,
    ProchainconcertList, ProchainconcertCreate, ProchainconcertUpdate,
    ConcertList, ConcertCreate, ConcertUpdate, ConcertDelete, 
    ShortList, ShortCreate, ShortUpdate, ShortDelete,
    LifestyleList, LifestyleCreate, LifestyleUpdate, LifestyleDelete,
    FormationList, FormationCreate, FormationUpdate, FormationDelete,
)

urlpatterns = [
    path('carrousel/', CarrouselList, name='CarrouselList'),
    path('carrousel/create/', CarrouselCreate, name='CarrouselCreate'),
    path('carrousel/update/<int:pk>/', CarrouselUpdate, name='CarrouselUpdate'),
    path('carrousel/delete/<int:pk>/', CarrouselDelete, name='CarrouselDelete'),
    path('morceau/', MorceauList, name='MorceauList'),
    path('morceau/create/', MorceauCreate, name='MorceauCreate'),
    path('morceau/update/<int:pk>/', MorceauUpdate, name='MorceauUpdate'),
    path('morceau/delete/<int:pk>/', MorceauDelete, name='MorceauDelete'),
    path('evenement/', EvenementList, name='EvenementList'),
    path('evenement/create/', EvenementCreate, name='EvenementCreate'),
    path('evenement/update/<int:pk>/', EvenementUpdate, name='EvenementUpdate'),
    path('evenement/delete/<int:pk>/', EvenementDelete, name='EvenementDelete'),
    path('audio/', AudioList, name='AudioList'),
    path('audio/create/', AudioCreate, name='AudioCreate'),
    path('audio/update/<int:pk>/', AudioUpdate, name='AudioUpdate'),
    path('audio/delete/<int:pk>/', AudioDelete, name='AudioDelete'),
    path('album/', AlbumList, name='AlbumList'),
    path('album/create/', AlbumCreate, name='AlbumCreate'),
    path('album/update/<int:pk>/', AlbumUpdate, name='AlbumUpdate'),
    path('album/delete/<int:pk>/', AlbumDelete, name='AlbumDelete'),
    path('discographie/', DiscographieList, name='DiscographieList'),
    path('discographie/create/', DiscographieCreate, name='DiscographieCreate'),
    path('discographie/update/<int:pk>/', DiscographieUpdate, name='DiscographieUpdate'),
    path('discographie/delete/<int:pk>/', DiscographieDelete, name='DiscographieDelete'),
    path('prochainconcert/', ProchainconcertList, name='ProchainconcertList'),
    path('prochainconcert/create/', ProchainconcertCreate, name='ProchainconcertCreate'),
    path('prochainconcert/update/<int:pk>/', ProchainconcertUpdate, name='ProchainconcertUpdate'),
    path('concert/', ConcertList, name='ConcertList'),
    path('concert/create/', ConcertCreate, name='ConcertCreate'),
    path('concert/update/<int:pk>/', ConcertUpdate, name='ConcertUpdate'),
    path('concert/delete/<int:pk>/', ConcertDelete, name='ConcertDelete'),
    path('short/', ShortList, name='ShortList'),
    path('short/create/', ShortCreate, name='ShortCreate'),
    path('short/update/<int:pk>/', ShortUpdate, name='ShortUpdate'),
    path('short/delete/<int:pk>/', ShortDelete, name='ShortDelete'),
    path('lifestyle/', LifestyleList, name='LifestyleList'),
    path('lifestyle/create/', LifestyleCreate, name='LifestyleCreate'),
    path('lifestyle/update/<int:pk>/', LifestyleUpdate, name='LifestyleUpdate'),
    path('lifestyle/delete/<int:pk>/', LifestyleDelete, name='LifestyleDelete'),
    path('formation/', FormationList, name='FormationList'),
    path('formation/create/', FormationCreate, name='FormationCreate'),
    path('formation/update/<int:pk>/', FormationUpdate, name='FormationUpdate'),
    path('formation/delete/<int:pk>/', FormationDelete, name='FormationDelete'),
    
]
